# Generated by Django 5.2.5 on 2025-09-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_remove_book_author_remove_library_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationship_app.library'),
        ),
    ]
