# Generated by Django 5.2.5 on 2025-09-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0006_alter_book_author_alter_book_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.AddField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(to='relationship_app.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
